
name: Run Tests
on: [push]
jobs:
  test-nim:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: jiro4989/setup-nim-action@v1
         with:
           nim-version: '1.6.10'
       - run: nimble test -Y
       
  test-py:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10' 
       - name: Install Dependencies  
         run: |
           pip install -U intenc
       - name: Run tests
         run: python pytests
       
  
